services:
  web:
    build: "./web_container"
    ports:
      - "80:80"
    volumes:
      - ./weblog_V0:/var/www/weblog_V0
      - ./apache_config/weblog.conf:/etc/apache2/sites-available/weblog.conf
    depends_on:
      - db
    restart: always
    command: >
      bash -c "chown www-data:www-data -R /var/www/weblog_V0 &&
               
               a2dissite default-ssl && a2dissite 000-default &&
               a2ensite weblog &&
               apache2-foreground"

    extra_hosts:
      - "host.docker.internal:host-gateway"   # Access host services

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: azerty
    volumes:
      - ./db_container/weblog.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
